[build]
  functions = "functions"

[[redirects]]
  from = "/*"
  to= "/dist/*"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to= "/.netlify/functions/index/"
  status = 200
  force = true

[build.environment]
  AWS_LAMBDA_JS_RUNTIME = "nodejs14.x"