[build]
  functions = "functions"

[[redirects]]
  from = "/*"
  to= "/dist/*"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to= "/.netlify/functions/index/"
  status = 200
  force = true